// reservation_frontend_angular/src/app/components/additional-list/additional-list.component.ts
import { Component, OnInit } from '@angular/core';
import { AdditionalService } from "../../services/additional-service/additional.service";
import { Additional } from "../../model/additional.model";
import { Router } from "@angular/router";

@Component({
  selector: 'app-additional-list',
  templateUrl: './additional-list.component.html',
  styleUrls: ['./additional-list.component.css']
})
export class AdditionalListComponent implements OnInit {
  additionals: Additional[] = [];
  paginatedAdditionals: Additional[] = [];
  currentPage: number = 1;
  itemsPerPage: number = 2;
  searchTerm: string = '';
  sortType: string = '';

  constructor(private additionalService: AdditionalService, public router: Router) { }

  ngOnInit(): void {
    this.fetchAdditionals();
  }

  fetchAdditionals(): void {
    this.additionalService.fetchAdditionals().subscribe(
      (data: Additional[]) => {
        this.additionals = data;
        this.sortData();
        this.updatePaginatedAdditionals();
      },
      (error) => {
        console.error('Error fetching additionals:', error);
      }
    );
  }

  editAdditional(additional: Additional) {
    this.router.navigate(['/main/edit-additional', additional.id])
  }

  onDelete(additionalId: number): void {
    this.additionalService.deleteAdditional(additionalId).subscribe({
      next: () => {
        console.log('Additional deleted successfully');
        this.fetchAdditionals()
      },
      error: (err) => {
        console.error('Error deleting additional:', err);
        // Handle the error appropriately
      }
    });
  }

  onPageChange(page: number): void {
    this.currentPage = page;
    this.updatePaginatedAdditionals();
  }

  onSearch(): void {
    this.sortType = ''; // Reset sort type when searching
    this.sortData();
    this.updatePaginatedAdditionals();
  }

  sortByName(): void {
    this.sortType = 'name';
    this.sortData();
    this.updatePaginatedAdditionals();
  }

  sortByPrice(): void {
    this.sortType = 'price';
    this.sortData();
    this.updatePaginatedAdditionals();
  }

  sortByAvailability(): void {
    this.sortType = 'availability';
    this.sortData();
    this.updatePaginatedAdditionals();
  }

  sortData(): void {
    if (this.sortType === 'name') {
      this.additionals.sort((a, b) => a.name.localeCompare(b.name));
    } else if (this.sortType === 'price') {
      this.additionals.sort((a, b) => a.price - b.price);
    } else if (this.sortType === 'availability') {
      this.additionals.sort((a, b) => a.available === b.available ? 0 : a.available ? -1 : 1);
    }
  }

  updatePaginatedAdditionals(): void {
    const startIndex = (this.currentPage - 1) * this.itemsPerPage;
    const endIndex = startIndex + this.itemsPerPage;
    this.paginatedAdditionals = this.additionals.slice(startIndex, endIndex);
  }
}

<div class="container">
  <div class="search-container">
    <input type="text" placeholder="Search..." [(ngModel)]="searchTerm" (input)="onSearch()">
  </div>
  <div class="button-container">
    <button mat-button color="primary" (click)="sortByName()">Sort by Name</button>
    <button mat-button color="primary" (click)="sortByPrice()">Sort by Price</button>
    <button mat-button color="primary" (click)="sortByAvailability()">Sort by Availability</button>
  </div>
  <div class="additionals-container">
    <div *ngFor="let additional of paginatedAdditionals" class="additional-item">
      <div class="attribute name">
        <p>{{ additional.name }}</p>
      </div>
      <div class="attribute">
        <p>Price: {{ additional.price }}</p>
      </div>
      <div class="attribute">
        <p>Available: {{ additional.available ? 'Yes' : 'No' }}</p>
      </div>
      <div class="attribute">
        <button mat-button color="primary" (click)="editAdditional(additional)">Edit</button>
      </div>
      <div class="attribute">
        <button mat-raised-button class="delete-button" (click)="onDelete(additional?.id || 0)">Delete</button>
      </div>
      <hr>
    </div>
  </div>
  <div class="pagination">
    <button (click)="onPageChange(currentPage - 1)" [disabled]="currentPage === 1">Previous</button>
    <span>{{ currentPage }}</span>
    <button (click)="onPageChange(currentPage + 1)" [disabled]="currentPage * itemsPerPage >= additionals.length">Next</button>
  </div>
</div>

// reservation_frontend_react/src/components/AdditionalList.js
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import '../styles/AdditionalList.css';

const AdditionalList = () => {
  const [additionals, setAdditionals] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [sortType, setSortType] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 2;
  const navigate = useNavigate();

  useEffect(() => {
    fetchAdditionals();
  }, []);

  const fetchAdditionals = async () => {
    try {
      const response = await axios.get('http://localhost:8080/api/v1/additional', {
        headers: { Authorization: `Bearer ${localStorage.getItem('access_token')}` },
      });
      setAdditionals(response.data);
    } catch (error) {
      console.error('Error fetching additionals:', error);
    }
  };

  const editAdditional = (additional) => {
    navigate(`/edit-additional/${additional.id}`);
  };

  const onDelete = async (id) => {
    try {
      await axios.delete(`http://localhost:8080/api/v1/additional/${id}`, {
        headers: { Authorization: `Bearer ${localStorage.getItem('access_token')}` },
      });
      fetchAdditionals(); // Refresh the list after deletion
    } catch (error) {
      console.error('Error deleting additional:', error);
    }
  };

  const onSearch = (e) => {
    setSearchTerm(e.target.value);
    setCurrentPage(1);
  };

  const filteredAdditionals = additionals.filter((additional) =>
    additional.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const sortedAdditionals = [...filteredAdditionals].sort((a, b) => {
    if (sortType === 'name') {
      return a.name.localeCompare(b.name);
    } else if (sortType === 'price') {
      return a.price - b.price;
    } else if (sortType === 'availability') {
      return a.available === b.available ? 0 : a.available ? -1 : 1;
    }
    return 0;
  });

  const paginatedAdditionals = sortedAdditionals.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const changePage = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  return (
    <div className="container">
      <div className="search-container">
        <input type="text" placeholder="Search..." value={searchTerm} onChange={onSearch} />
      </div>
      <div className="button-container">
        <button onClick={() => setSortType('name')}>Sort by Name</button>
        <button onClick={() => setSortType('price')}>Sort by Price</button>
        <button onClick={() => setSortType('availability')}>Sort by Availability</button>
      </div>
      <div className="additionals-container">
        {paginatedAdditionals.map((additional) => (
          <div key={additional.id} className="additional-item">
            <div className="attribute name">
              <p>{additional.name}</p>
            </div>
            <div className="attribute">
              <p>Price: {additional.price}</p>
            </div>
            <div className="attribute">
              <p>Available: {additional.available ? 'Yes' : 'No'}</p>
            </div>
            <div className="attribute">
              <button onClick={() => editAdditional(additional)}>Edit</button>
            </div>
            <div className="attribute">
              <button onClick={() => onDelete(additional.id)} className="delete-button">
                Delete
              </button>
            </div>
            <hr />
          </div>
        ))}
      </div>
      <div className="pagination">
        <button onClick={() => changePage(currentPage - 1)} disabled={currentPage === 1}>
          Previous
        </button>
        <span>{currentPage}</span>
        <button
          onClick={() => changePage(currentPage + 1)}
          disabled={currentPage * itemsPerPage >= filteredAdditionals.length}
          className="next-button"
        >
          Next
        </button>
      </div>
    </div>
  );
};

export default AdditionalList;
